name: TestFiles
options:
  bundleIdPrefix: com.dulcepalacios
settings:
  base:
    GCC_TREAT_WARNINGS_AS_ERRORS: YES
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks
fileGroups:
  # Allow the project xcodegen definition to be edited in Xcode.
  - project.yml
  - json
schemes:
  TestFiles:
    build:
      targets:
        TestFiles: all
targets:
  TestFiles:
    platform: iOS
    type: framework
    sources:
      - path: json